### ISSUE TITLE
errors when annotating models with postgis fields

### ISSUE THREAD

**Issue by abonec** [ctran/annotate_models#430]
ruby 2.3.1p112
rails 5.0.1
annotate 2.7.1
activerecord-postgis-adapter 4.0.0

schema for table:
```
  create_table "location", force: :cascade do |t|
    t.integer   "position"
    t.integer   "place_id",                                                                              null: false
    t.geography "geo_data",      limit: {:srid=>4326, :type=>"geometry", :geographic=>true}
    t.integer   "location_type",                                                             default: 1
    t.index "(COALESCE((st_startpoint((geo_data)::geometry))::geography, geo_data))", name: "geo_data_coalesce_ind", using: :gist
    t.index ["geo_data"], name: "geo_data_ind", using: :gist
    t.index ["place_id"], name: "index_location_on_place_id", using: :btree
  end
```

Last annotation of this model looks like:
```
# == Schema Information
#
# Table name: location
#
#  id            :integer          not null, primary key
#  position      :integer
#  place_id      :integer          not null
#  geo_data      :geography({:srid geometry, 4326
#  location_type :integer          default(1)
#
# Indexes
#
#  index_location_on_place_id  (place_id)
#
# Foreign Keys
#
#  fk_rails_8473fc2134  (place_id => place.id)
#
```

Error is:
```
rake db:migrate
Unable to annotate app/models/location.rb: undefined method `join' for #<String:0x000000055e9688>
Did you mean?  JSON
Unable to annotate app/models/location.rb: no implicit conversion of nil into Array
Model files unchanged.
```

**Comment by abonec** [comment]
@ctran I think this bug not related with geo but with indexes created by hand. These index definitions somehow appear in the schema as a strings, not arrays and annotate can't handle it.

The example in the first post.

**Comment by dv** [comment]
I have the same issue with custom constraints.

migration:
```
execute "CREATE EXTENSION btree_gist"
    execute <<-SQL
      ALTER TABLE custom_ad_time_slots
      ADD CONSTRAINT not_overlapping
      EXCLUDE USING gist
      (
        daterange(beginning_at, ending_at, '[)') WITH &&
      )
    SQL
```

structure.sql:
```
--
-- Name: custom_ad_time_slots not_overlapping; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY custom_ad_time_slots
    ADD CONSTRAINT not_overlapping EXCLUDE USING gist (daterange(beginning_at, ending_at, '[)'::text) WITH &&);
```

backtrace:
```
Unable to annotate app/models/custom_ad_time_slot.rb: undefined method `join' for "daterange(beginning_at, ending_at, '[)'::text)":String
Did you mean?  JSON
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:305:in `block in get_index_info'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:301:in `each'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:301:in `get_index_info'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:274:in `get_schema_info'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:463:in `annotate'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:613:in `annotate_model_file'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:598:in `block in do_annotations'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:597:in `each'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:597:in `do_annotations'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/bin/annotate:197:in `<top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/annotate:23:in `load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/annotate:23:in `<top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
	./bin/bundle:3:in `load'
	./bin/bundle:3:in `<main>'
Unable to annotate app/models/custom_ad_time_slot.rb: no implicit conversion of nil into Array
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:613:in `concat'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:613:in `annotate_model_file'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:598:in `block in do_annotations'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:597:in `each'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/lib/annotate/annotate_models.rb:597:in `do_annotations'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/annotate-2.7.1/bin/annotate:197:in `<top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/annotate:23:in `load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/annotate:23:in `<top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	/Users/david/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
	./bin/bundle:3:in `load'
	./bin/bundle:3:in `<main>'
Model files unchanged.
```

**Comment by dv** [comment]
Never mind, this issue was only with 2.7.1, it was fixed in 2.7.2 after updating! Sorry for the confusion.

**Comment by janosrusiczki** [comment]
I can reproduce the issue on:

ruby 2.5.3p105
rails 5.2.1
annotate 2.7.4
activerecord-postgis-adapter 5.2.1

I have the same problem:

    bounding_box      :geography({:srid geometry, 4326

**Comment by janosrusiczki** [comment]
@ctran I don't understand why you closed this as the issue still reproduces. Or am I doing something wrong?

**Comment by ctran** [comment]
I don't have the bandwidth or environment to look into issues related to postg.  You'll have to provide PR if you want this fixed.

**Comment by ctran** [comment]
This was closed due to @dv comment that it was fixed.
