### ISSUE TITLE
Unable to annotate a single file

### ISSUE THREAD

**Issue by amayer171** [ctran/annotate_models#525]
I'm using `v2.7.2` and attempting to annotate a single file which I know has changed. I'm using the command `annotate app/models/my_model.rb` in order to update that specific file.

I'm getting the error message 
```
TypeError: no implicit conversion of nil into String
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:646:in `join'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:646:in `block in do_annotations'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:645:in `each'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/annotate-2.7.2/lib/annotate/annotate_models.rb:645:in `do_annotations'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/annotate-2.7.2/bin/annotate:201:in `<top (required)>'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/annotate:22:in `load'
  /Users/me/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bin/annotate:22:in `<top (required)>'
```

My temporary fix is to lock the gem version to 2.6.10 which is known to work for annotating a single model.

I did try running `annotate` without specifying a file and it ran through all of the annotations successfully.

**Comment by ctran** [comment]
Can you try the latest version from the "develop" branch?  This should be fixed with #514

**Comment by remy727** [comment]
I am using `3.2.0` and this issue still happens. I can't annotate specific model file. No errors but nothing happens.
